name: bitcoinconverter.build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402

    - name: Install Dependencies
      run: cd C#/2-testing/BitcoinConverter && dotnet restore

    - name: Build
      run: cd C#/2-testing/BitcoinConverter && dotnet build --configuration Release --no-restore

    - name: Test
      run: cd C#/2-testing/BitcoinConverter && dotnet test --no-restore --verbosity normal

    - name: Generate Test Coverage Report
      run: |
        ls -la
        mkdir -p C#/2-testing/BitcoinConverter/BitcoinConverter.Tests/TestResults
        cd C#/2-testing/BitcoinConverter/BitcoinConverter.Tests
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

    - name: Publish Test Coverage Report
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: C#/2-testing/BitcoinConverter/BitcoinConverter.Tests/TestResults/coverage.info

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: BitcoinConverter.Code.dll
        path: C#/2-testing/BitcoinConverter/BitcoinConverter.Code/bin/Release/netcoreapp3.1/BitcoinConverter.Code.dll

    - name: Make Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files:
          C#/2-testing/BitcoinConverter/BitcoinConverter.Code/bin/Release/netcoreapp3.1/BitcoinConverter.Code.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}